version: "3.9"

services:
  web:
    build:
      context: ./micro_admin
      dockerfile: Dockerfile
    image: micro-admin:latest
    env_file:
      - ./micro_admin/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    # For Dokploy with Traefik, you can set labels here or in the UI
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.micro-admin.rule=Host(`admin.example.com`)"
    #   - "traefik.http.services.micro-admin.loadbalancer.server.port=8000"
    #   - "traefik.http.routers.micro-admin.tls=true"
    # networks:
    #   - web

# networks:
#   web:
#     external: true
