services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_SYNC_SERVICE_SID: ${TWILIO_SYNC_SERVICE_SID}
      PORT: ${PORT}

    ports:
      - ":8080"
    restart: unless-stopped
