services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      PORT: 8080
    ports:
      - ":8080"
    restart: unless-stopped
